model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 200
    feature_size: 1
    n_layer_enc: 2
    n_layer_dec: 2
    d_model: 64  # 4 X 16
    timesteps: 500
    fast_sampling: False
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 10000
  results_folder: ./Checkpoints
  gradient_accumulate_every: 2
  save_cycle: 1000
  ema:
    decay: 0.995
    update_interval: 10

  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500
      verbose: False


train:
  params:
    data_path: ./Data/datasets/Toy Example/top_example_seq_200_sample_10000.npy
    sample_number: 10000
    seq_length: 200
    batch_size: 64

sample:
  params:
    num_samples: 10000
    batch_size: 500
    auto_norm: False
